=== naufalhanif25/falhnf-site/public/works/works.schema.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "title": "Work List",
    "type": "array",
    "items": {
        "type": "object",
        "required": ["title", "description", "stack"],
        "properties": {
            "title": {
                "type": "string",
                "description": "Short project name"
            },
            "description": {
                "type": "string",
                "description": "Short project description"
            },
            "stack": {
                "type": "array",
                "description": "",
                "items": {
                    "type": "string",
                    "description": "Technologies used in the project"
                }
            },
            "source": {
                "type": "object",
                "description": "Links related to the project",
                "properties": {
                    "code": {
                        "type": "string",
                        "description": "Source code repository URL"
                    },
                    "app": {
                        "type": "string",
                        "description": "Deployed application URL"
                    }
                }
            }
        },
        "additionalProperties": false
    }
}

=== naufalhanif25/falhnf-site/public/works/works.json
[
    {
        "title": "WebinKuy",
        "description": "An affordable web development platform that helps businesses and individuals create websites with a simple and fast ordering process. It streamlines service requests from consultation to project delivery.",
        "stack": ["React", "Vite", "Sentry"],
        "source": {
            "code": "https://github.com/naufalhanif25/webinkuy-fe.git",
            "app": "https://webinkuy.vercel.app/"
        }
    },
    {
        "title": "HabaImbudee",
        "description": "A digital village portal designed to simplify administrative services and information access for Imbudee Village. It improves communication and public service efficiency for residents and village officials.",
        "stack": ["Next.js", "React", "Supabase"],
        "source": {
            "code": "https://github.com/naufalhanif25/haba-imbudee.git",
            "app": "https://habaimbudee.vercel.app/"
        }
    },
    {
        "title": "JakSabang",
        "description": "An integrated tourism platform for exploring destinations, accommodations, and transportation in Sabang. It provides a convenient booking system for lodging and vehicle rentals.",
        "stack": ["React", "Vite", "MongoDB", "Midtrans"],
        "source": {
            "code": "https://github.com/M-Aidil-Fitrah/JakSabang.git",
            "app": "https://jaksabang.com/"
        }
    }
]
